### PR TITLE
#111504508 Initial project setup

### PR DESCRIPTION
**Pull request by SEUNAGBEYE**
#### What does this PR do?
Setup a flask minimal application with minimal dependencies
#### Description of Task to be completed?
- Create the following folder structure
```
Initial project setup(flask application)
        api
            models
            views
            services
            utilities
   	hooks
    	seeders(will contain seeding code)
    	test(will contain all test code)
    	main.py(has methods for creating the flask app and wires all dependencies)
        config.py
    	manage.py
```
- Have the route ```Get /``` working

#### How should this be manually tested?
- Create a new virtualenv with python 3
- Activate the new environment
- Pull from this branch
- run ```pip install -r requirements.txt```
- Create a ```.env``` file at the root of the project directory
- Set the ```ENV=development``` in the ```.env``` file
- run ```python manage.py runserver```
- Hit the route ```GET /``` either on postman or on your web browser to receive the message ```Welcome to the AM api```
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
#157505088
#### Screenshots (if appropriate)
N/A
#### Questions:
N/A

### CODE REVIEW

**Comment by kodero** [comment]
Hey @SEUNAGBEYE, the PT board must have messed my order of the folders. 
`models`, `views`,  `services` and `utilities` are meant to be inside `api`. The rest are fine.

**Comment by SEUNAGBEYE** [comment]
@kodero, the folders are now in the correct order.

**Comment by kodero** [comment]
Great. Two points though
1) what does #111504508 represent?
2) Modify the PR description to reflect the agreed folder structure

**Comment by kodero** [comment]
@SEUNAGBEYE , the story ID is still not reflected on the PR title. Any reasons for that?

**Pull request closed without merging**
