### PR TITLE
#159130413 Allow cross-origin resource sharing

### PR DESCRIPTION
**Pull request by purpose50**
#### What does this PR do?
allow cross-origin resource sharing

#### Description of Task to be completed?
* install flask_cors
* initialize CORS with the flask app

#### How should this be manually tested?
make an ajax call to any of the application API

#### Any background context you want to provide?
N/A

#### Screenshots (if appropriate)
N/A

#### Questions:
N/A

### CODE REVIEW

**Comment by purpose50** [comment]
All done @brayoh

**Comment by purpose50** [comment]
Hi @ibutiti , I've set it up but it doesn't work. The same applies to everyone who has set it up on their system

**Comment by brayoh** [comment]
We should get on a call and fix the issue pre-commit hook issue cc @ibutiti

**Comment by brayoh** [comment]
@purpose50 did you update the pipenv file?

**Comment by purpose50** [comment]
@brayoh yes I did

**Pull request closed without merging**
