### PR TITLE
#159759387 Setup Sandbox

### PR DESCRIPTION
**Pull request by iidrees**
#### What does this PR do?
This PR adds a `type: approval` to the Circle CI `config.yml`  file

#### Description of Task to be completed?
- Add configuration that allows a sandbox be cleared out or destroyed after it has been used or before a new sandbox is going to be created.

#### How should this be manually tested?
Testing is done by Circle CI

#### Any background context you want to provide?
Currently the job pipeline has no pause mechanism that pauses the flow whenever a sandbox branch is created so this PR ensures that there is a pause at the `release to sandbox` stage and until the pipeline is `approved to continue` then it stays paused there.

#### What are the relevant pivotal tracker stories?
[#159759387 ](https://www.pivotaltracker.com/story/show/159759387)

#### Screenshots (if appropriate)
N/A
#### Questions:
N/A

### CODE REVIEW

**Comment by Thegaijin** [comment]
Your PR description doesn't match the change in the file.

**Comment by iidrees** [comment]
@Thegaijin it's been updated.

**Comment by Thegaijin** [comment]
LGTM

**Comment by iidrees** [comment]
Please, @Thegaijin could you also approve the PR? Thanks 🙇

**Pull request merged**
