### PR TITLE
#158290027 Create validation framework tests

### PR DESCRIPTION
**Pull request by ibutiti**
#### What does this PR do?
This PR adds in tests for the marshmallow validation framework and model instance delete validator.

#### Description of Task to be completed?
* Create tests for the validation framework, including the marshmallow base schemas and the model instance delete validator.

#### How should this be manually tested?
* Run `git checkout -b ch-validation-framework-tests` to create the branch on your local machine.
* Run `git pull ch-validation-framework-tests` to pull this code into your local machine.
* Run the command `pytest tests/test_validation_framework`

#### Any background context you want to provide?
None

#### What are the relevant pivotal tracker stories?
[#158290027](https://www.pivotaltracker.com/story/show/158290027)

#### Screenshots (if appropriate)
N/A

#### Questions:
N/A

### CODE REVIEW

**Comment by brayoh** [comment]
@ibutiti kindly update the ticket status and request for more reviews so that we can have this merged.

**Comment by brayoh** [comment]
1 small `NIT` for the `README` you don't have to create a new branch then pull the code into your local machine you can fetch from the remote into your local machine as follows `git fetch origin ch-ch-validation-framework-tests:ch-validation-framework-tests` then `git checkout ch-validation-framework-tests`

**Comment by brayoh** [comment]
Also rename branch to include the PT `ticket id`

**Comment by ibutiti** [comment]
@brayoh, we'd agreed as a team to use that git workflow for the readme part. Should we make the move to this convention?

**Pull request closed without merging**
